### ISSUE TITLE
Erreur de lecture - supprimer "2. Consultrer un restaurant existant" dans RestaurantCLI

### ISSUE THREAD

**Issue by cutiips** [cutiips/resto-order#23]
Console : 
Gestion des restaurants
0. Retour au menu principal
1. Ajouter un nouveau restaurant
2. Consulter un restaurant existant
3. Mettre à jour un restaurant
4. Supprimer un restaurant
5. Voir tous les restaurants
2
Choisissez un restaurant:
0. ID: 164 - Nom: Brasserie de Fribourg.
1. ID: 1 - Nom: Alpes Et Lac.
2. ID: 2 - Nom: Les Belgeries.
3. ID: 3 - Nom: Domino's Pizza.
4. ID: 163 - Nom: Brasserie du Jura.
164
Veuillez choisir un nombre entre 0 et 4.
0

**Comment by LudovicMarquis** [comment]
Tout bon, c'est corrigé.
